"""empty message

Revision ID: ec889eb82711
Revises: 
Create Date: 2021-10-17 18:14:08.180185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec889eb82711'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail', sa.Text(), nullable=True),
    sa.Column('nom', sa.Text(), nullable=True),
    sa.Column('prenom', sa.Text(), nullable=True),
    sa.Column('passworld', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=20), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('tel', sa.Text(), nullable=True),
    sa.Column('mail', sa.Text(), nullable=True),
    sa.Column('nonSite', sa.Text(), nullable=True),
    sa.Column('urlSite', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=20), nullable=True),
    sa.Column('prenom', sa.String(length=70), nullable=True),
    sa.Column('mail', sa.Text(), nullable=True),
    sa.Column('tel', sa.Integer(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commentaire_maison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenue', sa.Text(), nullable=True),
    sa.Column('Utilisateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commentaire_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenue', sa.Text(), nullable=True),
    sa.Column('Utilisateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.Text(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('longitude', sa.Integer(), nullable=True),
    sa.Column('lartitude', sa.Integer(), nullable=True),
    sa.Column('prix', sa.Text(), nullable=True),
    sa.Column('Agence_id', sa.Integer(), nullable=True),
    sa.Column('Categorie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Agence_id'], ['agence.id'], ),
    sa.ForeignKeyConstraint(['Categorie_id'], ['categorie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=True),
    sa.Column('Maison_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Maison_id'], ['maison.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_like',
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('commentaire_maison_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commentaire_maison_id'], ['commentaire_maison.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_like')
    op.drop_table('image')
    op.drop_table('maison')
    op.drop_table('commentaire_site')
    op.drop_table('commentaire_maison')
    op.drop_table('utilisateur')
    op.drop_table('categorie')
    op.drop_table('agence')
    op.drop_table('admin')
    # ### end Alembic commands ###
